name: Run Tests & Generate Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-allure-adf

      - name: Run tests
        run: |
          pytest --allure-reports-dir=./reports/allure-report

      - name: Generate report
        if: always() && success()
        run: |
          allure generate ./reports/allure-report -o reports/html --clean

      - name: Publish Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          echo "## Тестовые отчёты\n$(date)" >> README.md
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@example.com"
          git add .
          git commit -m "Update Test Reports"
          git remote set-url origin https://${GH_PAGES_TOKEN}@github.com/${{ github.repository }} > /dev/null 2>&1
          git push origin HEAD:${{ github.ref }}
